---
abstract: 'Common rules for searching DWG files.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Find-Rule-DWG
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  CAD::AutoCAD::Detect: 0
  File::Find::Rule: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-Find-Rule-DWG
  homepage: https://github.com/michal-josef-spacek/File-Find-Rule-DWG
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/File-Find-Rule-DWG
version: '0.01'
